# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: My Web Development Journey
domain: https://inshomothal.github.io/inshomohal.github.io/
email: trevonecollins@gmail.com
description: |
  **Welcome to My Web Development Journey.**

  ---

  **Introduction:**
    
  Hello, I'm Trevon Collins, a passionate and dynamic Web3 Developer with a focus on blockchain and decentralized finance (DeFi). Recently completing a comprehensive bootcamp, I've gained skills in creating smart contracts, building decentralized exchanges, and exploring key/value databases.

  ---

  **Skills Highlights:**

  - **Smart Contract Development:** Proficient in creating robust and efficient smart contracts.
  - **Decentralized Exchanges:** Successfully built a decentralized exchange, showcasing hands-on experience.
  - **Blockchain Technologies:** Eager to become proficient in Terra Blockchain and Cosmos SDK.

  ---

  **Projects Showcase:**

  - **Decentralized Exchange:** Developed a decentralized exchange to monitor token transactions, demonstrating commitment and innovation.

  ---

  **Aspirations:**

  Eager to apply my skills and passion to contribute to innovative projects at Terraform Labs. Excited about the opportunity to learn and become proficient in Terra Blockchain and Cosmos SDK.

  ---

  **Contact Information:**

  Connect with me on LinkedIn: [www.linkedin.com/in/trevon-collins-73286649](www.linkedin.com/in/trevon-collins-73286649)
  Email: trevonecollins@gmail.com
  GitHub: Inshomothal
  ---

  Thank you for visiting my page! I look forward to exciting opportunities and collaborations in the Web3 space.
baseurl: "inshomohal.github.io/docs" # the subpath of your site, e.g. /blog
url: "https://inshomothal.github.io/inshomohal.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: artietrey
github_username:  Inshomothal

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
